name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac80ccdf0abacf2d6a9391c3bc8924717647fb814386d918116404c6698bf38"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"

[options]
acceptable-game-versions = []
