name = "build/Commune"
author = "cwse"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffbaa2557fecccdc5d1a86af555040b156ddd24700ad656255157f6dc675d491"

[versions]
minecraft = "1.20.1"
quilt = "0.29.0"

[options]
acceptable-game-versions = []
