author = 'cwse'
name = 'build/Commune'
pack-format = 'packwiz:1.1.0'
version = '2.0.2'

[index]
  file = 'index.toml'
  hash = '6eb4668394a17ea26958a099a5fd3abee72a7b35164607e2969c55b78ccda243'
  hash-format = 'sha256'

[options]
  acceptable-game-versions = []

[versions]
  minecraft = '1.20.1'
  quilt = '0.28.0-beta.4'
