name = "Commune"
author = "cwse"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b430b88733e410823d4eae9a800988006420f036e5d04855d96c70964b6c24a"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
