name = "Commune"
author = "cwse"
version = "2.0.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ccfb501d8575b5c260108aeccd885556a502b0b943ba4d8393198a24753d30"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
