name = "Commune"
author = "cwse"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05ea63123673cac7e028fac5afb2da0cd8ab89963ab4114ce9fc7b18583daf1d"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
