author = 'cwse'
name = 'build/Commune'
pack-format = 'packwiz:1.1.0'
version = '2.0.3'

[index]
  file = 'index.toml'
  hash = '4ee98f933e482c6a35936bfd9c5505e68fec198ff53d3f5f0ecea6d1b3f162f6'
  hash-format = 'sha256'

[options]
  acceptable-game-versions = []

[versions]
  minecraft = '1.20.1'
  quilt = '0.29.0'
