author = 'cwse'
name = 'build/Commune'
pack-format = 'packwiz:1.1.0'
version = '2.0.3'

[index]
  file = 'index.toml'
  hash = 'df16e047f01bc47a14cadbac6952358f81476a7722fbd0b0c2421d649cac142b'
  hash-format = 'sha256'

[options]
  acceptable-game-versions = []

[versions]
  minecraft = '1.20.1'
  quilt = '0.29.0'
