name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a52e87205ff8345c8a58961175dbf2888d4b80cc2915a77e5cfd1935f213b04b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"

[options]
acceptable-game-versions = []
