author = 'cwse'
name = 'build/Commune'
pack-format = 'packwiz:1.1.0'
version = '2.0.3'

[index]
  file = 'index.toml'
  hash = 'de2ce6cf0f9e7776fa46df6aa80c5568edde726d867425eded5899fb6f6a62ad'
  hash-format = 'sha256'

[options]
  acceptable-game-versions = []

[versions]
  minecraft = '1.20.1'
  quilt = '0.29.0'
