name = "Commune"
author = "cwse"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63ec5f8d9be2931c10ab4b701c806fabd0148f6408db1592b40f4221fde35dd1"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
