name = "Commune"
author = "cwse"
version = "2.0.1l"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97b473655b9aa474c83d5a1aad75c88486d0885238412723e4e4d417529e7594"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
