name = "Commune"
author = "cwse"
version = "2.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75925a639c4a4b5580e6571c3dbb390dd295cebd91687dd15bac12d83c540b85"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
