name = "build/Commune"
author = "cwse"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0daa88c1e45f468d2cc0f950e14fc904c3ff1b11c01691bb9f104ba2b2c011"

[versions]
minecraft = "1.20.1"
quilt = "0.29.0"

[options]
acceptable-game-versions = []
