name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "676f80d02a1e07a586e9d5757f220f640ae79c26d48467e99addfde3ac7e30a7"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
