author = 'cwse'
name = 'build/Commune'
pack-format = 'packwiz:1.1.0'
version = '2.0.2'

[index]
  file = 'index.toml'
  hash = '44be15ca46003137f5f07e9709a7d6af401484e7d1e6c7bf472923e2e661a62c'
  hash-format = 'sha256'

[options]
  acceptable-game-versions = []

[versions]
  minecraft = '1.20.1'
  quilt = '0.28.0-beta.4'
