name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36c47aa48bdae38846a6d4c58d3f0b6582df1d64fdb3deda7cba10c500fa1b80"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"

[options]
acceptable-game-versions = []
