name = "Commune"
author = "cwse"
version = "2.0.2l"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a15426658ff1aa9e78a868f6323f41fd57a08d44551b536ad242e92fcd3a2bec"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
