name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "868ba47172bd77188502a7f986bd3e13e6c3e27b017d320047db627eaacc0651"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
