name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb8ba09c11713aa175e8ba31b8dba53717ba7b916d9fb5fead4cdf6e95f39e2c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"

[options]
acceptable-game-versions = []
