name = "Commune"
author = "cwse"
version = "2.0.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "923c4a4a9ddada1258152bc2e672593c635d4a62fa7f01bca52914a2b8ee0b30"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.4"

[options]
acceptable-game-versions = []
