name = "Commune"
author = "cwse"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e8e7a3e199ebca1ad16d61fd291082a2f375fc9ec798d62494a1cb3ae366f65"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"

[options]
acceptable-game-versions = []
