minimalLabelSize = false
deleteBoxesOnDisable = true
sendBoxes = true
showBoxesWhenDisabled = false
backgroundForLabels = true
reach = 50
incrementColor = false
innerDiagonal = false
showOtherUsersBoxes = true
colorIndex = 0
