minimalLabelSize = true
deleteBoxesOnDisable = true
sendBoxes = true
showBoxesWhenDisabled = false
backgroundForLabels = true
reach = 50
incrementColor = true
innerDiagonal = true
showOtherUsersBoxes = true
colorIndex = 0
