[general]
announce_new_song = 0
link_mode = 1
first_time = true
mod_mode = -1
notification_album_art_location = 1
music_service = "spotify"
announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"

[servers]
allowed_servers = ""
send_songs_to_servers = false

[rendering]
controls = true
display_mode = 1
position_x_offset = 1.0
position_y_offset = 1.0
anchor_point = 7
render_type = 6

[login]
refresh_token = ""
spotify_login_token = ""
ytmd_token = ""
service_port = 8880
