[air]
	#Range: > 1
	uses_per_tank = 2048
	#Range: > 1
	uses_per_tank_hover = 20480
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======

>>>>>>> 535d858 (init)
>>>>>>> 59f1721 (init)
[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.02
	#Range: 0.01 ~ 100.0
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 59f1721 (init)
	acceleration = 0.6
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8
	#Range: 0.01 ~ 100.0
	vertical = 0.4
	#Range: -100.0 ~ 0.0
	hover_descend = -0.03
<<<<<<< HEAD
=======
=======
	vertical = 0.4
	#Range: 0.01 ~ 100.0
	acceleration = 0.6
	#Range: -100.0 ~ 0.0
	hover_descend = -0.03
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8

>>>>>>> 535d858 (init)
>>>>>>> 59f1721 (init)
[features]
	#Range: 1.0 ~ 100.0
	elytra_boost = 1.25
