#.
#Settings which are more fun and not fit for survival
[minigame]
	#.
	#Enable/Disable all minigame settings
	minigameEnabled = true
	#.
	#Gives you permanent, unremovable Girl Power Effect
	permaDash = true
	#.
	#The level of Girl Power Effect when Perma-Dash is enabled
	#Range: 0 ~ 255
	permaDashAmount = 2
