#.
#Settings which are more fun and not fit for survival
[minigame]
	#.
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
	#Enable/Disable all minigame settings
	minigameEnabled = true
	#.
>>>>>>> 535d858 (init)
>>>>>>> 59f1721 (init)
	#Gives you permanent, unremovable Girl Power Effect
	permaDash = true
	#.
	#The level of Girl Power Effect when Perma-Dash is enabled
	#Range: 0 ~ 255
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 59f1721 (init)
	permaDashAmount = 2
	#.
	#Enable/Disable all minigame settings
	minigameEnabled = true
<<<<<<< HEAD
=======
=======
	permaDashAmount = 5
>>>>>>> 535d858 (init)
>>>>>>> 59f1721 (init)
